version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: '*'
      update-types:
      - version-update:semver-major
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "monthly"
