services:
  frontend:
    image: my-dotnet-app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://foo:bar@db:5432/moviedb
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
